use ffmpeg::palettes::palette::Palette;

#[derive(clap::ValueEnum, Clone, Debug, PartialEq, strum::Display)]
pub enum StaticPalette {
	Cmyk, // actually CMYK plus white
	Windows,
	Macintosh,
	Websafe,
	UniformPs, // Photoshop's Uniform palette

	// these palettes were generated by reducing all 24-bit colors to just 256 colors using:
	UniformAseprite,   // Aseprite's Octree method
	UniformFfmpeg,     // ffmpeg's palettegen
	UniformPerceptual, // Photoshop's Perceptual method
	UniformSelective,  // Photoshop's Selective method

	// by Adigun Polack
	// https://twitter.com/AdigunPolack
	AAP64,      // https://pixeljoint.com/pixelart/119466.htm
	AAPMicro12, // https://pixeljoint.com/pixelart/121151.htm
	AAPRadiantXV,
	AAPSplendor128, // https://pixeljoint.com/pixelart/120714.htm
	SimpleJPC16,    // https://pixeljoint.com/pixelart/119844.htm

	// by Arne Niklas Jansson
	// https://androidarts.com/palette/16pal.htm
	A64,
	ARNE16,
	ARNE32,
	CgArne,
	CopperTech,
	CpcBoy,
	ErogeCopper,
	Jmp,
	Psygnosia,

	// by Davit Masia
	// https://twitter.com/DavitMasia
	Matriax8c,

	// by Richard "DawnBringer" Fhager
	// https://hem.fyristorg.com/dawnbringer/
	DB8,  // https://pixeljoint.com/forum/forum_posts.asp?TID=26050
	DB16, // https://pixeljoint.com/forum/forum_posts.asp?TID=12795
	DB32, // https://pixeljoint.com/forum/forum_posts.asp?TID=16247

	// by ENDESGA Studios
	// https://twitter.com/ENDESGA
	ARQ4,
	ARQ16,
	EDG8,
	EDG16,
	EDG32,
	EN4,
	ENOS16,
	HEPT32,

	// by Hyohnoo
	// https://twitter.com/Hyohnoo
	Mail24,

	// by Javier Guerrero
	// https://twitter.com/Xavier_Gd
	Nyx8,

	// by Joseph White
	// https://www.pico-8.com/
	Pico8,

	// by PineTreePizza
	// https://twitter.com/PineTreePizza
	Bubblegum16,
	Rosy42,

	// by Zughy
	// https://twitter.com/_Zughy
	Zughy32,

	// Hardware Palettes
	// https://github.com/aseprite/aseprite/tree/8323a555007e1db9670b098ce4b1b9c5f8b3d7ad/data/extensions/hardware-palettes
	AppleII,
	Atari2600Ntsc,
	Atari2600Pal,
	Cga,
	Cga0,
	Cga0High,
	Cga1,
	Cga1High,
	Cga3rd,
	Cga3rdHigh,
	CommodorePlus4,
	CommodoreVic20,
	Commodore64,
	Cpc,
	Gameboy,
	GameboyColor,
	MasterSystem,
	MSX1,
	MSX2,
	Nes,
	NesNtsc,
	Teletext,
	VGA13h,
	VirtualBoy,
	ZXSpectrum,

	// Software Palettes
	// https://github.com/aseprite/aseprite/tree/8323a555007e1db9670b098ce4b1b9c5f8b3d7ad/data/extensions/software-palettes
	GoogleUI,
	Minecraft,
	Monokai,
	SmileBasic,
	Solarized,
	Win16,
	X11,
}

#[rustfmt::skip]
impl StaticPalette {
	pub fn to_palette(&self) -> Palette {
		match self {
			StaticPalette::Cmyk => Palette::from(vec![0x0, 0xffff00, 0x00ffff, 0xff00ff, 0xffffff]),
			StaticPalette::Windows => Palette::from_hex_string(include_str!("palettes/windows.hex")).unwrap(),
			StaticPalette::Macintosh => Palette::from_hex_string(include_str!("palettes/macintosh.hex")).unwrap(),
			StaticPalette::Websafe => Palette::from_hex_string(include_str!("palettes/websafe.hex")).unwrap(),
			StaticPalette::UniformPs => Palette::from_hex_string(include_str!("palettes/photoshop_uniform.hex")).unwrap(),

			StaticPalette::UniformAseprite => Palette::from_hex_string(include_str!("palettes/uniform_aseprite.hex")).unwrap(),
			StaticPalette::UniformFfmpeg => Palette::from_hex_string(include_str!("palettes/uniform_ffmpeg.hex")).unwrap(),
			StaticPalette::UniformPerceptual => Palette::from_hex_string(include_str!("palettes/uniform_perceptual.hex")).unwrap(),
			StaticPalette::UniformSelective => Palette::from_hex_string(include_str!("palettes/uniform_selective.hex")).unwrap(),

			StaticPalette::AAP64 => Palette::from_gpl_string(include_str!("palettes/adigunpolack-palettes/aap-64.gpl")).unwrap(),
			StaticPalette::AAPMicro12 => Palette::from_gpl_string(include_str!("palettes/adigunpolack-palettes/aap-micro12.gpl")).unwrap(),
			StaticPalette::AAPRadiantXV => Palette::from_gpl_string(include_str!("palettes/adigunpolack-palettes/aap-radiantxv.gpl")).unwrap(),
			StaticPalette::AAPSplendor128 => Palette::from_gpl_string(include_str!("palettes/adigunpolack-palettes/aap-splendor128.gpl")).unwrap(),
			StaticPalette::SimpleJPC16 => Palette::from_gpl_string(include_str!("palettes/adigunpolack-palettes/simplejpc-16.gpl")).unwrap(),

			StaticPalette::A64 => Palette::from_gpl_string(include_str!("palettes/arne-palettes/a64.gpl")).unwrap(),
			StaticPalette::ARNE16 => Palette::from_gpl_string(include_str!("palettes/arne-palettes/arne16.gpl")).unwrap(),
			StaticPalette::ARNE32 => Palette::from_gpl_string(include_str!("palettes/arne-palettes/arne32.gpl")).unwrap(),
			StaticPalette::CgArne => Palette::from_gpl_string(include_str!("palettes/arne-palettes/cg-arne.gpl")).unwrap(),
			StaticPalette::CopperTech => Palette::from_gpl_string(include_str!("palettes/arne-palettes/copper-tech.gpl")).unwrap(),
			StaticPalette::CpcBoy => Palette::from_gpl_string(include_str!("palettes/arne-palettes/cpc-boy.gpl")).unwrap(),
			StaticPalette::ErogeCopper => Palette::from_gpl_string(include_str!("palettes/arne-palettes/eroge-copper.gpl")).unwrap(),
			StaticPalette::Jmp => Palette::from_gpl_string(include_str!("palettes/arne-palettes/jmp.gpl")).unwrap(),
			StaticPalette::Psygnosia => Palette::from_gpl_string(include_str!("palettes/arne-palettes/psygnosia.gpl")).unwrap(),

			StaticPalette::Matriax8c => Palette::from_gpl_string(include_str!("palettes/davitmasia-palettes/matriax8c.gpl")).unwrap(),

			StaticPalette::DB8 => Palette::from_gpl_string(include_str!("palettes/dawnbringer-palettes/db8.gpl")).unwrap(),
			StaticPalette::DB16 => Palette::from_gpl_string(include_str!("palettes/dawnbringer-palettes/db16.gpl")).unwrap(),
			StaticPalette::DB32 => Palette::from_gpl_string(include_str!("palettes/dawnbringer-palettes/db32.gpl")).unwrap(),

			StaticPalette::ARQ4 => Palette::from_gpl_string(include_str!("palettes/endesga-palettes/arq4.gpl")).unwrap(),
			StaticPalette::ARQ16 => Palette::from_gpl_string(include_str!("palettes/endesga-palettes/arq16.gpl")).unwrap(),
			StaticPalette::EDG8 => Palette::from_gpl_string(include_str!("palettes/endesga-palettes/edg8.gpl")).unwrap(),
			StaticPalette::EDG16 => Palette::from_gpl_string(include_str!("palettes/endesga-palettes/edg16.gpl")).unwrap(),
			StaticPalette::EDG32 => Palette::from_gpl_string(include_str!("palettes/endesga-palettes/edg32.gpl")).unwrap(),
			StaticPalette::EN4 => Palette::from_gpl_string(include_str!("palettes/endesga-palettes/en4.gpl")).unwrap(),
			StaticPalette::ENOS16 => Palette::from_gpl_string(include_str!("palettes/endesga-palettes/enos16.gpl")).unwrap(),
			StaticPalette::HEPT32 => Palette::from_gpl_string(include_str!("palettes/endesga-palettes/hept32.gpl")).unwrap(),

			StaticPalette::Mail24 => Palette::from_gpl_string(include_str!("palettes/hyohnoo-palettes/mail24.gpl")).unwrap(),

			StaticPalette::Nyx8 => Palette::from_gpl_string(include_str!("palettes/javierguerrero-palettes/nyx8.gpl")).unwrap(),

			StaticPalette::Pico8 => Palette::from_gpl_string(include_str!("palettes/pico8-palette/pico-8.gpl")).unwrap(),

			StaticPalette::Bubblegum16 => Palette::from_gpl_string(include_str!("palettes/pinetreepizza-palettes/bubblegum-16.gpl")).unwrap(),
			StaticPalette::Rosy42 => Palette::from_gpl_string(include_str!("palettes/pinetreepizza-palettes/rosy-42.gpl")).unwrap(),

			StaticPalette::Zughy32 => Palette::from_gpl_string(include_str!("palettes/zughy-palettes/zughy-32.gpl")).unwrap(),

			StaticPalette::AppleII => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/apple-ii.gpl")).unwrap(),
			StaticPalette::Atari2600Ntsc => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/atari2600-ntsc.gpl")).unwrap(),
			StaticPalette::Atari2600Pal => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/atari2600-pal.gpl")).unwrap(),
			StaticPalette::Cga => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/cga.gpl")).unwrap(),
			StaticPalette::Cga0 => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/cga0.gpl")).unwrap(),
			StaticPalette::Cga0High => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/cga0hi.gpl")).unwrap(),
			StaticPalette::Cga1 => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/cga1.gpl")).unwrap(),
			StaticPalette::Cga1High => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/cga1hi.gpl")).unwrap(),
			StaticPalette::Cga3rd => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/cga3rd.gpl")).unwrap(),
			StaticPalette::Cga3rdHigh => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/cga3rdhi.gpl")).unwrap(),
			StaticPalette::CommodorePlus4 => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/commodore-plus4.gpl")).unwrap(),
			StaticPalette::CommodoreVic20 => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/commodore-vic20.gpl")).unwrap(),
			StaticPalette::Commodore64 => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/commodore64.gpl")).unwrap(),
			StaticPalette::Cpc => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/cpc.gpl")).unwrap(),
			StaticPalette::Gameboy => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/gameboy.gpl")).unwrap(),
			StaticPalette::GameboyColor => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/gameboy-color-type1.gpl")).unwrap(),
			StaticPalette::MasterSystem => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/master-system.gpl")).unwrap(),
			StaticPalette::MSX1 => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/msx1.gpl")).unwrap(),
			StaticPalette::MSX2 => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/msx2.gpl")).unwrap(),
			StaticPalette::Nes => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/nes.gpl")).unwrap(),
			StaticPalette::NesNtsc => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/nes-ntsc.gpl")).unwrap(),
			StaticPalette::Teletext => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/teletext.gpl")).unwrap(),
			StaticPalette::VGA13h => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/vga-13h.gpl")).unwrap(),
			StaticPalette::VirtualBoy => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/virtualboy.gpl")).unwrap(),
			StaticPalette::ZXSpectrum => Palette::from_gpl_string(include_str!("palettes/hardware-palettes/zx-spectrum.gpl")).unwrap(),

			StaticPalette::GoogleUI => Palette::from_gpl_string(include_str!("palettes/software-palettes/google-ui.gpl")).unwrap(),
			StaticPalette::Minecraft => Palette::from_gpl_string(include_str!("palettes/software-palettes/minecraft.gpl")).unwrap(),
			StaticPalette::Monokai => Palette::from_gpl_string(include_str!("palettes/software-palettes/monokai.gpl")).unwrap(),
			StaticPalette::SmileBasic => Palette::from_gpl_string(include_str!("palettes/software-palettes/smile-basic.gpl")).unwrap(),
			StaticPalette::Solarized => Palette::from_gpl_string(include_str!("palettes/software-palettes/solarized.gpl")).unwrap(),
			StaticPalette::Win16 => Palette::from_gpl_string(include_str!("palettes/software-palettes/win16.gpl")).unwrap(),
			StaticPalette::X11 => Palette::from_gpl_string(include_str!("palettes/software-palettes/x11.gpl")).unwrap(),
		}
	}
}
